/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefinitionsCanvasJson {
  [k: string]: any;
}
/**
 * This interface was referenced by `DefinitionsCanvasJson`'s JSON-Schema
 * via the `definition` "Canvas".
 */
export interface Canvas {
  designResolution: {
    width: number;
    height: number;
    [k: string]: any;
  };
  [k: string]: any;
}
