/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefinitionsComponentReferenceJson {
  [k: string]: any;
}
/**
 * This interface was referenced by `DefinitionsComponentReferenceJson`'s JSON-Schema
 * via the `definition` "ComponentReference".
 */
export interface ComponentReference {
  nodeId: number;
  componentId: number;
  [k: string]: any;
}
