/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefinitionsRendererJson {
  [k: string]: any;
}
/**
 * This interface was referenced by `DefinitionsRendererJson`'s JSON-Schema
 * via the `definition` "Renderer".
 */
export interface Renderer {
  color?: {
    r: number;
    g: number;
    b: number;
    a: number;
    [k: string]: any;
  };
  [k: string]: any;
}
