/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefinitionsScrollBarJson {
  [k: string]: any;
}
/**
 * This interface was referenced by `DefinitionsScrollBarJson`'s JSON-Schema
 * via the `definition` "ScrollBar".
 */
export interface ScrollBar {
  handleNodeId?: string;
  scrollViewNodeId?: string;
  enableAutoHide?: boolean;
  autoHideTime?: number;
  direction?: string;
  [k: string]: any;
}
