/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefinitionsTransform3DJson {
  [k: string]: any;
}
/**
 * This interface was referenced by `DefinitionsTransform3DJson`'s JSON-Schema
 * via the `definition` "Transform3D".
 */
export interface Transform3D {
  x: number;
  y: number;
  z: number;
  rotation: {
    x: number;
    y: number;
    z: number;
    w?: number;
    [k: string]: any;
  };
  scale?: {
    x: number;
    y: number;
    z: number;
    [k: string]: any;
  };
  parent?: string;
  children?: string[];
  [k: string]: any;
}
