/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefinitionsEventJson {
  [k: string]: any;
}
/**
 * This interface was referenced by `DefinitionsEventJson`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  targetId: string;
  type: string;
  callback: string;
  params?: string[];
  [k: string]: any;
}
